# Generated by Django 2.2.3 on 2020-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('available_flg', models.BooleanField(default=True)),
                ('description_flg', models.TextField()),
            ],
        ),
    ]
