# Generated by Django 2.2.3 on 2020-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='pic_id',
        ),
        migrations.AddField(
            model_name='pic',
            name='category',
            field=models.CharField(default='OTHER', max_length=255),
        ),
    ]
